### ISSUE TITLE
AdGuard DNS (Regular) prevent Windows Quick Assistant to connect

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardSDNSFilter#765]
### Steps to reproduce

1. Configure DNS settings (System or via Adguard app)
2. Try to open `Windows quick assist`
3. Assistant [can't connect](https://uploads.adguard.com/Chinaskir3czv.png) to the server

> Note: The issue reproduce only if you using a Regular server

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 94.140.14.14 / 94.140.15.15)
| How did you setup DNS configuration:| (System/AdGuard app 7.7 beta)
| Operating system and version:| (Windows 10 x64)

**Comment by AdamWr** [comment]
Should be fixed in a few hours.

**Comment by ilion1** [comment]
Hi,
just ran into the same problem yesterday. I am using Adguard DNS service on Keenetic routers. Switching to regular DNS resolves the problem immediately. So the problem either still exists or has reappeared.

**Comment by ilion1** [comment]
Hi,

 

thanks for following up. I do not know whether it is that domain only. However I just know that Quick Assist does not start and is sitting there with a circle as long as I am using Adguard DNS and will work with ISP provided DNS. Quick Assist will most likely use some sort of load balancing, fault tolerance, cdn setup and not rely on a single DNS address.

 

Seems to be an issue with other DNS ad blockers like Pi-Hole: Can't launched Microsoft Quick Assist : pihole (reddit.com)

 

Klaus

 
 

Gesendet: Donnerstag, 05. Mai 2022 um 16:45 Uhr
Von: "Alex" ***@***.***>
An: "AdguardTeam/AdGuardSDNSFilter" ***@***.***>
Cc: "ilion1" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [AdguardTeam/AdGuardSDNSFilter] AdGuard DNS (Regular) prevent Windows Quick Assistant to connect (#765)


 

Hi.
We do not block this domain
Details

**Comment by Alex-302** [comment]
@ckarson Hi. 

> The version is v0.107.6.

AdGuard Home? Could you please unblock `monitor.azure.com` using Query Log and check again?

**Comment by Alex-302** [comment]
Will be fixed by https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/949

**Comment by ilion1** [comment]
Quick Assist can be used again with AdGuard DNS running.

 

Von: Alex ***@***.***> 
Gesendet: Freitag, 6. Mai 2022 00:06
An: AdguardTeam/AdGuardSDNSFilter ***@***.***>
Cc: ilion1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [AdguardTeam/AdGuardSDNSFilter] AdGuard DNS (Regular) prevent Windows Quick Assistant to connect (#765)

 

Will be fixed by #949 <https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/949>
